name: "Label from issue first message body"
# See https://github.com/marketplace/actions/regex-issue-labeler

on:
  issues:
    types: [opened, edited]

jobs:
  triage:
    runs-on: ubuntu-18.04
    steps:
    - uses: github/issue-labeler@v2.2
      with:
        # Secret token needed (not sure which permisions though)
        repo-token: "${{ secrets.GH_TOKEN }}"
        # File with label/regex match dictionary
        configuration-path: .github/labeler.yml
        # The issues opened before this date will be ignored
        not-before: 2020-10-29T00:00:00Z
        # This can be increased if the dictionary undergoes a breaking change
        enable-versioned-regex: 0
